# Generated by Django 3.0.5 on 2020-04-01 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0003_auto_20200401_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('cats', models.ManyToManyField(related_name='feedings', to='cats.Cat', verbose_name='cats')),
                ('feeder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedings', to=settings.AUTH_USER_MODEL, verbose_name='feeder')),
            ],
            options={
                'verbose_name': 'feeding',
                'verbose_name_plural': 'feedings',
                'ordering': ('-created',),
            },
        ),
    ]
