# Generated by Django 3.0.5 on 2020-04-01 16:18

import autoslug.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('feeders', models.ManyToManyField(related_name='cats', to=settings.AUTH_USER_MODEL, verbose_name='feeders')),
            ],
            options={
                'verbose_name': 'cat',
                'verbose_name_plural': 'cats',
            },
        ),
    ]
