# Generated by Django 3.0.5 on 2020-04-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20200401_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ('name',), 'verbose_name': 'cat', 'verbose_name_plural': 'cats'},
        ),
    ]
